"use client";

import { useEffect, useMemo, useState } from "react";
import { api, ApiError } from "@/lib/api";
import type { SchemaEntry } from "@/lib/types";
import { ConfirmDialog, Drawer, EmptyState, MetricStrip, PageHero, StatusBadge } from "@/components/ui";

const EMPTY: {name:string;kind:"input"|"output";json_schema_text:string} = {name:"",kind:"output",json_schema_text:'{\n  "type": "object",\n  "properties": {}\n}'};
export default function SchemasPage() {
  const [schemas,setSchemas]=useState<SchemaEntry[]>([]),[form,setForm]=useState(EMPTY),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const [query,setQuery]=useState(""),[kind,setKind]=useState<"all"|"input"|"output">("all"),[creating,setCreating]=useState(false),[selected,setSelected]=useState<SchemaEntry|null>(null),[deleting,setDeleting]=useState<SchemaEntry|null>(null);
  async function load(){setLoading(true);setSchemas(await api.get<SchemaEntry[]>("/schemas"));setLoading(false);} useEffect(()=>{load();},[]);
  async function handleCreate(e:React.FormEvent){e.preventDefault();setError("");let parsed;try{parsed=JSON.parse(form.json_schema_text);}catch{setError("Schema must be valid JSON");return;}try{await api.post("/schemas",{name:form.name,kind:form.kind,json_schema:parsed});setForm(EMPTY);setCreating(false);await load();}catch(err){setError(err instanceof ApiError?err.message:String(err));}}
  async function handleDelete(){if(!deleting)return;await api.del(`/schemas/${deleting.id}`);setDeleting(null);setSelected(null);await load();}
  const visible=useMemo(()=>schemas.filter((schema)=>(kind==="all"||schema.kind===kind)&&schema.name.toLowerCase().includes(query.toLowerCase())),[kind,query,schemas]);
  return <div className="page"><PageHero eyebrow="Data contracts" title="Schemas" description="Define predictable inputs and structured outputs for every agent run." actions={<button className="btn" onClick={()=>setCreating(true)}>+ New schema</button>}/><MetricStrip items={[{value:schemas.length,label:"Total schemas"},{value:schemas.filter(s=>s.kind==="input").length,label:"Input schemas"},{value:schemas.filter(s=>s.kind==="output").length,label:"Output schemas"}]}/><div className="ds-toolbar"><label className="ds-search"><span className="sr-only">Search schemas</span><input placeholder="Search schemas…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="ds-segmented">{(["all","input","output"] as const).map(item=><button key={item} className={kind===item?"active":""} onClick={()=>setKind(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div></div>
  {loading?<div className="ds-skeleton-card"/>:visible.length?<div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Name</th><th>Kind</th><th>Version</th><th></th></tr></thead><tbody>{visible.map(schema=><tr key={schema.id}><td data-label="Name"><button className="table-link" onClick={()=>setSelected(schema)}><span className="ds-table-primary">{schema.name}</span><span className="ds-table-sub">Structured JSON contract</span></button></td><td data-label="Kind"><StatusBadge tone={schema.kind==="output"?"info":"neutral"}>{schema.kind}</StatusBadge></td><td data-label="Version">v{schema.version}</td><td data-label="Actions"><div className="ds-table-actions"><button className="btn btn-secondary" onClick={()=>setSelected(schema)}>Preview</button><button className="btn btn-danger" onClick={()=>setDeleting(schema)}>Delete</button></div></td></tr>)}</tbody></table></div>:<EmptyState icon="{}" title={query?"No matching schemas":"Create a data contract"} description={query?"Try a different name or kind filter.":"Define the information your agents receive and the exact structure they return."} action={!query&&<button className="btn" onClick={()=>setCreating(true)}>Create schema</button>}/>}
  <Drawer open={creating} title="Create schema" subtitle="Data contracts" onClose={()=>setCreating(false)} footer={<><button className="btn btn-secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="btn" form="create-schema" type="submit">Create schema</button></>}><form id="create-schema" onSubmit={handleCreate}>{error&&<p className="form-error">{error}</p>}<div className="field"><label>Name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Kind</label><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as "input"|"output"})}><option value="input">Input</option><option value="output">Output</option></select></div><div className="field"><label>JSON Schema</label><textarea className="ds-code" required rows={16} value={form.json_schema_text} onChange={e=>setForm({...form,json_schema_text:e.target.value})}/></div></form></Drawer>
  <Drawer open={!!selected} title={selected?.name||"Schema"} subtitle={`${selected?.kind||""} schema · v${selected?.version||""}`} onClose={()=>setSelected(null)}>{selected&&<pre className="ds-code">{JSON.stringify(selected.json_schema,null,2)}</pre>}</Drawer><ConfirmDialog open={!!deleting} title="Delete this schema?" description="Agent versions using this schema may be affected. This action cannot be undone." onClose={()=>setDeleting(null)} onConfirm={handleDelete}/></div>;
}
