"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { api,ApiError } from "@/lib/api";
import type { Agent,ContentItem } from "@/lib/types";
import { ConfirmDialog,Drawer,EmptyState,MetricStrip,PageHero,StatusBadge } from "@/components/ui";

export default function ContentStorePage(){
 const [agents,setAgents]=useState<Agent[]>([]),[agentId,setAgentId]=useState(""),[items,setItems]=useState<ContentItem[]>([]),[file,setFile]=useState<File|null>(null),[error,setError]=useState(""),[uploading,setUploading]=useState(false),[loading,setLoading]=useState(true),[drawer,setDrawer]=useState(false),[deleting,setDeleting]=useState<ContentItem|null>(null);
 useEffect(()=>{api.get<Agent[]>("/agents").then(a=>{setAgents(a);if(a.length)setAgentId(a[0].id);else setLoading(false);});},[]);
 async function loadItems(id:string){if(!id)return;setLoading(true);setItems(await api.get<ContentItem[]>(`/content?agent_id=${id}`));setLoading(false);} useEffect(()=>{loadItems(agentId);},[agentId]);
 async function handleUpload(e:React.FormEvent){e.preventDefault();if(!file||!agentId)return;setError("");setUploading(true);const data=new FormData();data.append("file",file);try{await api.post(`/content?agent_id=${agentId}`,data);setFile(null);setDrawer(false);await loadItems(agentId);}catch(err){setError(err instanceof ApiError?err.message:String(err));}finally{setUploading(false);}}
 async function handleDelete(){if(!deleting)return;await api.del(`/content/${deleting.id}`);setDeleting(null);await loadItems(agentId);}
 const currentAgent=agents.find(a=>a.id===agentId);
 return <div className="page"><PageHero eyebrow="Knowledge base" title="Content Store" description="Upload trusted documents that agents can search during a run." actions={<button className="btn" disabled={!agentId} onClick={()=>setDrawer(true)}>+ Upload document</button>}/><MetricStrip items={[{value:items.length,label:"Documents"},{value:agents.length,label:"Agents"},{value:currentAgent?.name||"—",label:"Selected agent"}]}/>{agents.length?<div className="ds-toolbar"><div className="field content-agent-filter"><label>Knowledge for agent</label><select value={agentId} onChange={e=>setAgentId(e.target.value)}>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><Link href="/tools" className="btn btn-secondary">View document search tool</Link></div>:null}
 {loading?<div className="ds-skeleton-card"/>:!agents.length?<EmptyState icon="A" title="Create an agent first" description="Content is attached to an agent so its document-search tool knows which knowledge to use." action={<Link className="btn" href="/agents/new">Create agent</Link>}/>:items.length?<div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Document</th><th>Agent</th><th>Status</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td data-label="Document"><span className="ds-table-primary">{item.filename}</span><span className="ds-table-sub">PDF or text document</span></td><td data-label="Agent">{currentAgent?.name}</td><td data-label="Status"><StatusBadge tone="success">Ready</StatusBadge></td><td data-label="Actions"><div className="ds-table-actions"><button className="btn btn-danger" onClick={()=>setDeleting(item)}>Delete</button></div></td></tr>)}</tbody></table></div>:<EmptyState icon="↥" title="No documents yet" description="Upload policies, manuals, notes, or reference material for this agent." action={<button className="btn" onClick={()=>setDrawer(true)}>Upload document</button>}/>}
 <Drawer open={drawer} title="Upload document" subtitle={currentAgent?.name||"Knowledge base"} onClose={()=>setDrawer(false)} footer={<><button className="btn btn-secondary" onClick={()=>setDrawer(false)}>Cancel</button><button className="btn" form="upload-content" type="submit" disabled={!file||uploading}>{uploading?"Uploading…":"Upload"}</button></>}><form id="upload-content" onSubmit={handleUpload}>{error&&<p className="form-error">{error}</p>}<label className="upload-dropzone"><span>↥</span><strong>{file?file.name:"Choose a PDF or text file"}</strong><small>Files are extracted and made searchable for this agent.</small><input type="file" accept=".pdf,.txt,text/plain,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></form></Drawer><ConfirmDialog open={!!deleting} title="Delete this document?" description="The agent will no longer be able to search this content." onClose={()=>setDeleting(null)} onConfirm={handleDelete}/></div>;
}
