"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {api,ApiError} from "@/lib/api";
import type {McpServer,McpTool} from "@/lib/types";
import {ConfirmDialog,Drawer,EmptyState,LoadingGrid,MetricStrip,PageHero,StatusBadge} from "@/components/ui";
export default function McpServersPage(){
 const [servers,setServers]=useState<McpServer[]>([]),[tools,setTools]=useState<Record<string,McpTool[]>>({}),[form,setForm]=useState({name:"",url:"",secret_ref:""}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[syncing,setSyncing]=useState<string|null>(null),[deleting,setDeleting]=useState<McpServer|null>(null);
 async function load(){setLoading(true);const list=await api.get<McpServer[]>("/mcp-servers");setServers(list);const entries=await Promise.all(list.map(async s=>[s.id,await api.get<McpTool[]>(`/mcp-servers/${s.id}/tools`)] as const));setTools(Object.fromEntries(entries));setLoading(false);}useEffect(()=>{load();},[]);
 async function handleCreate(e:React.FormEvent){e.preventDefault();setError("");try{await api.post("/mcp-servers",{...form,secret_ref:form.secret_ref||null});setForm({name:"",url:"",secret_ref:""});setCreating(false);await load();}catch(err){setError(err instanceof ApiError?err.message:String(err));}}
 async function handleSync(id:string){setSyncing(id);setError("");try{await api.post(`/mcp-servers/${id}/sync`);await load();}catch(err){setError(err instanceof ApiError?err.message:String(err));}finally{setSyncing(null);}}
 async function handleDelete(){if(!deleting)return;await api.del(`/mcp-servers/${deleting.id}`);setDeleting(null);await load();}
 const totalTools=Object.values(tools).reduce((sum,list)=>sum+list.length,0);
 return <div className="page"><PageHero eyebrow="External capabilities" title="MCP Servers" description="Connect remote Model Context Protocol servers and discover their tools automatically." actions={<button className="btn" onClick={()=>setCreating(true)}>+ Register server</button>}/><MetricStrip items={[{value:servers.length,label:"Connected servers"},{value:totalTools,label:"Discovered tools"},{value:servers.filter(s=>s.secret_ref).length,label:"Authenticated"}]}/>{error&&<p className="form-error alert-box">{error}</p>}{loading?<LoadingGrid/>:servers.length?<div className="ds-card-grid">{servers.map(server=><article className="ds-resource-card" key={server.id}><div className="ds-card-top"><span className="ds-card-icon">M</span><StatusBadge tone={(tools[server.id]||[]).length?"success":"warning"}>{(tools[server.id]||[]).length?"connected":"no tools"}</StatusBadge></div><h3>{server.name}</h3><span className="ds-card-meta">{server.url}</span><p>{(tools[server.id]||[]).length?`${(tools[server.id]||[]).map(t=>t.tool_name).join(", ")}`:"Sync this server to discover available tools."}</p><div className="ds-card-actions"><button className="btn btn-secondary" disabled={syncing===server.id} onClick={()=>handleSync(server.id)}>{syncing===server.id?"Syncing…":"Re-sync"}</button><button className="btn btn-danger" onClick={()=>setDeleting(server)}>Delete</button></div></article>)}</div>:<EmptyState icon="M" title="Connect your first MCP server" description="Register a streamable HTTP endpoint to make its tools available to agents." action={<button className="btn" onClick={()=>setCreating(true)}>Register server</button>}/>}<Drawer open={creating} title="Register MCP server" subtitle="External capabilities" onClose={()=>setCreating(false)} footer={<><button className="btn btn-secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="btn" type="submit" form="create-mcp">Register and sync</button></>}><form id="create-mcp" onSubmit={handleCreate}>{error&&<p className="form-error">{error}</p>}<div className="field"><label>Name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Streamable HTTP URL</label><input required placeholder="https://example.com/mcp" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></div><div className="field"><div className="field-label-row"><label>Credential reference (optional)</label><Link className="field-action-link" href="/secrets" target="_blank">Manage keys ↗</Link></div><input value={form.secret_ref} onChange={e=>setForm({...form,secret_ref:e.target.value})}/></div></form></Drawer><ConfirmDialog open={!!deleting} title="Delete this MCP server?" description="Its discovered tools will no longer be available to agents." onClose={()=>setDeleting(null)} onConfirm={handleDelete}/></div>;
}
