"use client";
import {useEffect,useState} from "react";import {useParams,useRouter} from "next/navigation";import Link from "next/link";import {api} from "@/lib/api";import type {Agent,AgentTrigger,AgentVersion,EvaluationDataset,EvaluationRun,Run} from "@/lib/types";import {ConfirmDialog,EmptyState,MetricStrip,PageHero,StatusBadge} from "@/components/ui";import EvaluationWorkspace from "@/components/EvaluationWorkspace";
const TABS=["Overview","Harness","Triggers","Evaluation","Versions","Runs"];
export default function AgentDetailPage(){const {id:agentId}=useParams<{id:string}>(),router=useRouter();const [tab,setTab]=useState(0),[agent,setAgent]=useState<Agent|null>(null),[versions,setVersions]=useState<AgentVersion[]>([]),[triggers,setTriggers]=useState<AgentTrigger[]>([]),[runs,setRuns]=useState<Run[]>([]),[datasets,setDatasets]=useState<EvaluationDataset[]>([]),[evalRuns,setEvalRuns]=useState<EvaluationRun[]>([]),[loading,setLoading]=useState(true),[confirmDelete,setConfirmDelete]=useState(false);
 async function load(){const[a,v,t,r,d]=await Promise.all([api.get<Agent>(`/agents/${agentId}`),api.get<AgentVersion[]>(`/agents/${agentId}/versions`),api.get<AgentTrigger[]>(`/agents/${agentId}/triggers`),api.get<Run[]>(`/runs?agent_id=${agentId}`),api.get<EvaluationDataset[]>(`/agents/${agentId}/evaluation-datasets`)]);setAgent(a);setVersions(v);setTriggers(t);setRuns(r);setDatasets(d);setLoading(false);}useEffect(()=>{load();},[agentId]);async function handleDelete(){await api.del(`/agents/${agentId}`);router.push("/agents");}async function handlePublish(){const draft=versions.find(v=>!v.is_published);if(!draft)return;await api.post(`/agents/${agentId}/versions/${draft.id}/publish`);await load();}async function runEvaluation(datasetId:string){const version=versions.find(v=>v.is_published)||versions[0];if(!version)return;const result=await api.post<EvaluationRun>(`/agents/${agentId}/versions/${version.id}/evaluate?dataset_id=${datasetId}`);setEvalRuns([...evalRuns,result]);}if(loading||!agent)return <p className="page-loading">Loading…</p>;const draft=versions.find(v=>!v.is_published),published=versions.find(v=>v.is_published);
 return <div className="page agent-detail-page"><PageHero eyebrow={`Agent · ${agent.agent_type}`} title={agent.name} description={agent.description||"No description has been added for this agent."} actions={<><Link className="btn btn-secondary" href={`/agents/${agentId}/edit`}>Edit</Link><Link className="btn btn-secondary" href={`/agents/${agentId}/playground`}>Playground</Link>{draft&&<button className="btn" onClick={handlePublish}>Publish draft</button>}<button className="btn btn-danger" onClick={()=>setConfirmDelete(true)}>Delete</button></>}/><div className="agent-status-line"><StatusBadge tone={agent.status==="active"?"success":"warning"}>{agent.status}</StatusBadge>{agent.domain&&<StatusBadge>{agent.domain}</StatusBadge>}{agent.tags.map(tag=><StatusBadge key={tag}>{tag}</StatusBadge>)}</div><MetricStrip items={[{value:versions.length,label:"Versions"},{value:triggers.length,label:"Triggers"},{value:runs.length,label:"Runs"},{value:agent.evaluation_gate_enabled?"On":"Off",label:"Evaluation gate"}]}/><div className="tabs ds-tabs" role="tablist">{TABS.map((label,index)=><button key={label} className={`tab ${tab===index?"active":""}`} onClick={()=>setTab(index)}>{label}</button>)}</div><section className="agent-tab-panel">
 {tab===0&&<div className="overview-grid"><div className="ds-form-section"><h3>Agent profile</h3><dl className="detail-list"><div><dt>Owner</dt><dd>{agent.owner||"Not assigned"}</dd></div><div><dt>Domain</dt><dd>{agent.domain||"General"}</dd></div><div><dt>Type</dt><dd>{agent.agent_type}</dd></div><div><dt>Status</dt><dd>{agent.status}</dd></div></dl></div><div className="ds-form-section"><h3>Runtime readiness</h3><dl className="detail-list"><div><dt>Published version</dt><dd>{published?`v${published.version_number}`:"Not published"}</dd></div><div><dt>Provider</dt><dd>{(published||draft)?.harness_config.runtime_model.provider||"Not configured"}</dd></div><div><dt>Model</dt><dd>{(published||draft)?.harness_config.runtime_model.model_id||"Not configured"}</dd></div><div><dt>Evaluation</dt><dd>{agent.evaluation_gate_enabled?"Required":"Optional"}</dd></div></dl></div></div>}
 {tab===1&&<div className="ds-form-section"><h3>Harness configuration</h3>{draft||published?<pre className="ds-code">{JSON.stringify((draft||published)?.harness_config,null,2)}</pre>:<EmptyState title="No harness configured" description="Open the editor to select a model, prompt, schema, and tools."/>}</div>}
 {tab===2&&(triggers.length?<div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Name</th><th>Type</th><th>Status</th></tr></thead><tbody>{triggers.map(t=><tr key={t.id}><td data-label="Name"><span className="ds-table-primary">{t.name}</span></td><td data-label="Type">{t.type}</td><td data-label="Status"><StatusBadge tone={t.enabled?"success":"neutral"}>{t.enabled?"enabled":"disabled"}</StatusBadge></td></tr>)}</tbody></table></div>:<EmptyState title="No triggers configured" description="Open the agent editor to add a manual, API, or scheduled trigger."/>)}
 {tab===3&&<EvaluationWorkspace agentId={agentId} versions={versions}/>}
 {tab===4&&(versions.length?<div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Version</th><th>Status</th><th>Published</th></tr></thead><tbody>{versions.map(v=><tr key={v.id}><td data-label="Version"><span className="ds-table-primary">v{v.version_number}</span></td><td data-label="Status"><StatusBadge tone={v.is_published?"success":"warning"}>{v.is_published?"published":"draft"}</StatusBadge></td><td data-label="Published">{v.published_at?new Date(v.published_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div>:<EmptyState title="No versions" description="Configure this agent to create its first draft version."/>)}
 {tab===5&&(runs.length?<div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Run</th><th>Status</th><th>Completed</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td data-label="Run"><span className="ds-table-primary">#{r.id.slice(0,8)}</span></td><td data-label="Status"><StatusBadge tone={r.status==="completed"?"success":r.status==="failed"?"danger":"info"}>{r.status}</StatusBadge></td><td data-label="Completed">{r.completed_at?new Date(r.completed_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div>:<EmptyState title="No runs yet" description="Open the Playground to test this agent." action={<Link className="btn" href={`/agents/${agentId}/playground`}>Open Playground</Link>}/>)}
 </section><ConfirmDialog open={confirmDelete} title="Delete this agent?" description="All versions and configuration belonging to this agent will be removed permanently." onClose={()=>setConfirmDelete(false)} onConfirm={handleDelete}/></div>}
